---
title: "Homework 2"
author: "Chris Lynum"
date: "September 23, 2015"
output: html_document
---

## Part 1 - Make these plots!

Making plots using the gampinder dataset.
Plot are made up of layers, just like ogres.

### Plot 1

```{r}
# load the libraries that I will be using
library(gapminder)
library(ggplot2)
library(dplyr)
```



```{r}
plot1 <- ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp,
                                      color = continent))
# Jillian, I made the backbone of the plot and wanted to color
## by continent
plot1 + geom_point(aes(shape = factor(continent)))
# here I added a layer of the points with diff. shapes
```

### Plot 2

```{r}
# log the shit out of the data
plot2 <- ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp,
                                      color = continent))
plot2 + geom_point(aes(shape = factor(continent)))
# fuck yeah
```

### Plot 3

```{r}
plot3 <- ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp))
plot3 + geom_point(aes(shape = factor(continent),
                       color = continent)) + 
  stat_smooth(method = 'lm')
# had to specify to do coloring by continent in geom_point
# if I kept it within the original ggplot() there would be a stat_smooth
## line for every continent individiually
```

### Plot 4

```{r}
plot4 <- ggplot(data = gapminder, aes(x = lifeExp, fill = continent ))
plot4 + geom_density(alpha = .5) + facet_wrap(~ year)
# fill = continent in the ggplot() otherwise can't get black outline
## from geom_density
```


### Plot 5

```{r}
plot5 <- ggplot(data = gapminder, aes(x = continent, y = lifeExp,
                                      color = continent))
plot5 + geom_boxplot() + facet_wrap(~ year) +
  coord_flip() 
```




### Plot 6 - ish
```{r}
# Want to plot life expectancy
# use dplyr to include aggregate values
# use subset() to select/exclude parts of the dataset

gapminder %>%
  ggplot(aes(x = lifeExp, fill = continent)) + 
  geom_density(alpha = 0.5)

# plot6 <- ggplot(data = gapminder, aes(x = lifeExp, fill = continent ))
# plot6 + geom_density(aes(alpha = .3))
```

### Plot 7

```{r}
#subset(airquality, Temp > 80, select = c(Ozone, Temp))
#subset(airquality, Day == 1, select = -Temp)
#subset(airquality, select = Ozone:Wind)

ggplot(data = subset(gapminder, continent %in% c("Asia")),
       aes(x = lifeExp, fill = continent)) +
  geom_density(fill = 'green', alpha = 0.5) +
  geom_vline(data = subset(gapminder,
                           continent %in% c("Asia")),
             aes(xintercept = mean(lifeExp))) +
  ggtitle("Life expectancy in Asia")

```


### Plot 8
```{r}
ggplot(gapminder, aes(x = lifeExp)) + 
  geom_density(aes(fill = continent), alpha = 0.5) + 
  geom_vline(data = ddply(gapminder, 'continent', summarize,
                          mean_life = mean(lifeExp)),
             aes(xintercept = mean_life)) +
  facet_wrap(~ continent)
```


```{r}
# Create a data frame of mean lifeExp for each continent
df8 <- group_by(gapminder, continent) %>%
  summarize(mean_life = mean(lifeExp))
df8
mean(gapminder$lifeExp)

ggplot(gapminder, aes(x = lifeExp)) +
  geom_density() + geom_vline(xintercept = df8[,2]) + 
  facet_wrap(~ continent)

```

```{r}
# have to aggregate means out to plot
#gapminder %>%
#  group_by(continent) %>%
#  mutate()
plot8 <- ggplot(data = gapminder, aes(x = lifeExp),
                color = continent)
plot8 + geom_density() + geom_vline(xintercept =
                                      mean(gapminder$lifeExp)) +
  facet_wrap(~continent)
  
```


## Part 3 - Find the mistakes

```{r}
setwd('~/R_Projects/PCinR/Homework_Lynum')
hw_gapminder <- read.csv('hw_gapminder.csv')
```

```{r}
mean_lifeExp <- mean(hw_gapminder$lifeExp)
# want to find the mean of all life expectancy
mean_lifeExp
# Jillian, you spelled lifeExp wrong. 
```


```{r}
small_set <- hw_gapminder[c(1, 2, 3, 4, 1300:1305),
c('country', 'continent', 'year')]
small_set
# You foroget the c before the country, continent, year
```


```{r}
mean_gdp <- mean(hw_gapminder$gdpPercap, na.rm = T)
# I want to find the mean of the gdpPercap of all the data
mean_gdp
# You sneakily put in NAs. You jerk.
```

```{r}
max_country <- hw_gapminder$country[which(hw_gapminder$lifeExp == 
                                            max(hw_gapminder$lifeExp))]
max_country
# You have to use double equals (==), duh. 
```

